Added questions to FAQ
DHP-stottepakke/pages pull request #41
Opened 2024-02-27 12:38 UTC by kjemist

2024-03-01 14:51 UTC, jennyostrop requested changes
Hei Illimar, Kan du vurdere å skrive litt mer under de overskriftene som ikke har fått tekst? Evt. rydde bort noen av de. Tror det er best å begrense seg på de punktene vi kan sie noe om, vil se veldig uferdig ut ellers.

2024-03-07 10:37 UTC, kjemist commented on pages/dmp_knowledge_base/difficult_faq.md
> +Ideally, a DMP should be as filled out as much as possible before a grant application is written. Mapping out aspects of the research life cycle as early as possible will make it easier for you to ha
Addec content + commented ("<!--- -->") out questions

2024-03-08 12:15 UTC, jennyostrop requested changes

2024-03-08 12:15 UTC, jennyostrop commented on pages/dmp_knowledge_base/difficult_faq.md
> +### What format should I store my research data in?
Does not really fit in this section? (see also additional information in https://dhp-stottepakke.github.io/pages/1_data_description)

2024-03-08 12:15 UTC, jennyostrop commented on pages/dmp_knowledge_base/difficult_faq.md
> +### What metadata should I consider collecting in my reseach project?
Does not really fit in this section? (see also additional information in https://dhp-stottepakke.github.io/pages/2_documentation_quality)

2024-03-08 12:15 UTC, jennyostrop commented on pages/dmp_knowledge_base/difficult_faq.md
> +Ideally, a DMP should be as filled out as much as possible before the active phase of the project starts and some aspects should alreday be in place at the proposal stage. Mapping out aspects of the
```suggestion
Ideally, a DMP should be as filled out as much as possible before the active phase of the project starts and some aspects should alreday be in place at the proposal stage. Mapping out aspects of the research life cycle as early as possible will make it easier for you to have an idea of which data should be gathered while conducting the research project. For example; deciding early on which data repository you will submit the data to for long storage will give you an idea of which metadata will be necessary to gather in order to submit to the relevant archive.

The DMP should be updated as the project develops and decisions taken, it should be considered 'a living document'. Scheduling regular updates is recommended, either at given timepoints or in connections with milestones in the project.
```

2024-09-10 09:12 UTC, jennyostrop approved these changes

2024-09-10 09:12 UTC, merged