added embargo
DHP-stottepakke/pages pull request #94
Opened 2024-09-17 12:14 UTC by livek

lagt til beskrivelse av embargo

2024-09-17 13:06 UTC, korbinib requested changes
tried to add clarification

2024-09-17 13:06 UTC, korbinib commented on pages/dmp_supporting_info/support_00_rdm_terms.md
> +> A given period of time which defines when the data will be made available in an open archive.
```suggestion
> A given period of time which defines when the data will be made available in an open archive after it has been deposited already.
```

2024-09-23 11:44 UTC, jennyostrop approved these changes

2024-09-23 11:45 UTC, jennyostrop approved these changes

2024-09-23 12:00 UTC, korbinib approved these changes

2024-09-23 12:00 UTC, merged