Updated knowledge base faq page
DHP-stottepakke/pages pull request #98
Opened 2024-09-25 16:09 UTC by jennyostrop

Closes #17

2024-09-27 12:18 UTC, korbinib reviewed
See suggestion

2024-09-27 12:18 UTC, korbinib commented on index.html
> +                      <h2 class="no-anchor text-center mb-3"> Information about data management planning </h2>
```suggestion
                      <h2 class="no-anchor text-center mb-3"> Further information </h2>

```
The whole page is about RDM or not?

2024-09-30 08:10 UTC, korbinib requested changes

2024-09-30 08:10 UTC, korbinib commented on index.html
> +                      <h2 class="no-anchor text-center mb-3"> Information about data management planning </h2>
```suggestion
                      <h2 class="no-anchor text-center mb-3"> About data management planning </h2>

```

2024-09-30 09:09 UTC, korbinib approved these changes

2024-09-30 11:58 UTC, merged

2024-09-30 11:59 UTC, sveinho reviewed
Look good